# Generated by Django 2.1 on 2018-08-13 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='facebookPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fbUsername', models.CharField(max_length=20)),
                ('fbContent', models.CharField(max_length=2000)),
                ('fbDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='instagramPosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('igUsername', models.CharField(max_length=20)),
                ('igContent', models.CharField(max_length=300)),
                ('igDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='twitterTweets',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twUsername', models.CharField(max_length=20)),
                ('twContent', models.CharField(max_length=280)),
                ('twDate', models.DateTimeField(verbose_name='date published')),
            ],
        ),
    ]
